# Generated by Django 3.2 on 2021-05-02 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("calendar_event", "0001_initial"),
        ("room", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="room.conferenceroom",
                verbose_name="event_location",
            ),
        ),
    ]
