# Generated by Django 3.2 on 2021-05-02 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("calendar_event", "0002_event_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_owner",
                to=settings.AUTH_USER_MODEL,
                verbose_name="event_owner",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="event_participants",
                to=settings.AUTH_USER_MODEL,
                verbose_name="event_participants",
            ),
        ),
    ]
